name: linux-package

on:
  push:
    tags:
      - 'v*'

jobs:
  standalone-build:
    name: Build Standalone Version
    # Because linuxdeployqt only supports ubuntu 22.04, not support higher version like 24.04
    runs-on: ubuntu-22.04
    env:
      QT_VERSION: 6.10.0
      BUILD_TYPE: Release
      BUILD_VARIANT: standalone

    steps:
      - name: Checkout Source code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          cache: true
          cache-key-prefix: 'Qt'

      - name: Configure CMake for Standalone
        run: cmake -B ${{ github.workspace }}/build-${{ env.BUILD_VARIANT }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DENABLE_SYNC_FEATURE=OFF

      - name: Build Standalone
        run: cmake --build ${{ github.workspace }}/build-${{ env.BUILD_VARIANT }} --config ${{ env.BUILD_TYPE }}

      - name: Install AppImage dependencies (Linux)
        # Ubuntu (>= 24.04) is libfuse2t64, otherwise is libfuse2
        run: |
          UBUNTU_VER=$(lsb_release -rs)   # 24.04 / 22.04 / 20.04
          echo "Ubuntu $UBUNTU_VER detected"

          case "$UBUNTU_VER" in
            24.04)
              sudo apt-get install -y libfuse2t64
              ;;
            22.04)
              sudo apt-get install -y libfuse2
              ;;
            *)
              echo "Untested Ubuntu version: $UBUNTU_VER"
              ;;
          esac

      - name: Run Packaging Script for Standalone
        run: |
          python3 scripts/build_linux_package.py --output-dir ${{ github.workspace }}/build-${{ env.BUILD_VARIANT }}/src --app-name Floward --format appimage

      - name: Upload Standalone Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Floward-Linux-Standalone
          path: ${{ github.workspace }}/build-${{ env.BUILD_VARIANT }}/src/Floward*.AppImage
          retention-days: 7

  sync-build:
    name: Build Sync Version
    # Because linuxdeployqt only supports ubuntu 22.04, not support higher version like 24.04
    runs-on: ubuntu-22.04
    env:
      QT_VERSION: 6.10.0
      BUILD_TYPE: Release
      BUILD_VARIANT: sync

    steps:
      - name: Checkout Source code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          cache: true
          cache-key-prefix: 'Qt'
          modules: 'qtwebsockets'

      - name: Configure CMake for Sync
        run: cmake -B ${{ github.workspace }}/build-${{ env.BUILD_VARIANT }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DENABLE_SYNC_FEATURE=ON

      - name: Build Sync
        run: cmake --build ${{ github.workspace }}/build-${{ env.BUILD_VARIANT }} --config ${{ env.BUILD_TYPE }}

      - name: Install AppImage dependencies (Linux)
        # Ubuntu (>= 24.04) is libfuse2t64, otherwise is libfuse2
        run: |
          UBUNTU_VER=$(lsb_release -rs)   # 24.04 / 22.04 / 20.04
          echo "Ubuntu $UBUNTU_VER detected"

          case "$UBUNTU_VER" in
            24.04)
              sudo apt-get install -y libfuse2t64
              ;;
            22.04)
              sudo apt-get install -y libfuse2
              ;;
            *)
              echo "Untested Ubuntu version: $UBUNTU_VER"
              ;;
          esac

      - name: Run Packaging Script for Sync
        run: |
          python3 scripts/build_linux_package.py --output-dir ${{ github.workspace }}/build-${{ env.BUILD_VARIANT }}/src --app-name Floward --format appimage

      - name: Upload Sync Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Floward-Linux-Sync
          path: ${{ github.workspace }}/build-${{ env.BUILD_VARIANT }}/src/Floward*.AppImage
          retention-days: 7

  create-release:
    name: Create Release
    needs: [standalone-build, sync-build]
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest

    steps:
      - name: Download Standalone Artifact
        uses: actions/download-artifact@v4
        with:
          name: Floward-Linux-Standalone
          path: ./artifacts

      - name: Download Sync Artifact
        uses: actions/download-artifact@v4
        with:
          name: Floward-Linux-Sync
          path: ./artifacts

      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./artifacts/Floward*.AppImage
          draft: false
          prerelease: false
          generate_release_notes: true
